schema = 3

[mod]
  [mod."github.com/bytedance/sonic"]
    version = "v1.14.0"
    hash = "sha256-caxXESTGRVGIOMyhgZTVxjVTyoT7LkGdPjQh17H7S7Y="
  [mod."github.com/bytedance/sonic/loader"]
    version = "v0.3.0"
    hash = "sha256-nYgehtTjd3INGcLqwKKzXEmjIbKYlpeDnYwewH/pskQ="
  [mod."github.com/cloudwego/base64x"]
    version = "v0.1.6"
    hash = "sha256-VzYJsGubsDk3FAMH6e0Xk0Cl4HtUFHHmWkVASUYidsI="
  [mod."github.com/gabriel-vasile/mimetype"]
    version = "v1.4.8"
    hash = "sha256-ElqfQtnoGHyVqtN0mJjeWakQ6N5x+nVaX3+uOV7Q5Xk="
  [mod."github.com/gin-contrib/sse"]
    version = "v1.1.0"
    hash = "sha256-2VP6zHEsPi0u2ZYpOTcLulwj1Gsmb6oA19qcP2/AzVM="
  [mod."github.com/gin-gonic/gin"]
    version = "v1.11.0"
    hash = "sha256-tFP0u7TZyB1V8b1mdnTWMrfdcwzf9yO86RZr026K8Ao="
  [mod."github.com/go-playground/locales"]
    version = "v0.14.1"
    hash = "sha256-BMJGAexq96waZn60DJXZfByRHb8zA/JP/i6f/YrW9oQ="
  [mod."github.com/go-playground/universal-translator"]
    version = "v0.18.1"
    hash = "sha256-2/B2qP51zfiY+k8G0w0D03KXUc7XpWj6wKY7NjNP/9E="
  [mod."github.com/go-playground/validator/v10"]
    version = "v10.27.0"
    hash = "sha256-S6RXBwCOaLUumtS1xucTzOPGxA9XuA3R8RNdGE7w2Qc="
  [mod."github.com/goccy/go-json"]
    version = "v0.10.2"
    hash = "sha256-6fMD2/Rku8HT0zDdeA23pX0YxbohiIOC8OJNYbylJTQ="
  [mod."github.com/goccy/go-yaml"]
    version = "v1.18.0"
    hash = "sha256-7WH1WraWyGj7SvrOCnZkWdoGOVrQ9dkpj/zrckHq9+I="
  [mod."github.com/gomarkdown/markdown"]
    version = "v0.0.0-20250810172220-2e2c11897d1a"
    hash = "sha256-DEVYXsGwyqgTwvxkqs7RDQVF6HpPO4zMW9jyAPg27I4="
  [mod."github.com/json-iterator/go"]
    version = "v1.1.12"
    hash = "sha256-To8A0h+lbfZ/6zM+2PpRpY3+L6725OPC66lffq6fUoM="
  [mod."github.com/klauspost/cpuid/v2"]
    version = "v2.3.0"
    hash = "sha256-50JhbQyT67BK38HIdJihPtjV7orYp96HknI2VP7A9Yc="
  [mod."github.com/leodido/go-urn"]
    version = "v1.4.0"
    hash = "sha256-Q6kplWkY37Tzy6GOme3Wut40jFK4Izun+ij/BJvcEu0="
  [mod."github.com/mattn/go-isatty"]
    version = "v0.0.20"
    hash = "sha256-qhw9hWtU5wnyFyuMbKx+7RB8ckQaFQ8D+8GKPkN3HHQ="
  [mod."github.com/modern-go/concurrent"]
    version = "v0.0.0-20180228061459-e0a39a4cb421"
    hash = "sha256-+bdeHUArnpkk4eMQIwXm9K249NkpwAjoTrXrGn/4VUE="
  [mod."github.com/modern-go/reflect2"]
    version = "v1.0.2"
    hash = "sha256-+W9EIW7okXIXjWEgOaMh58eLvBZ7OshW2EhaIpNLSBU="
  [mod."github.com/pelletier/go-toml/v2"]
    version = "v2.2.4"
    hash = "sha256-8qQIPldbsS5RO8v/FW/se3ZsAyvLzexiivzJCbGRg2Q="
  [mod."github.com/quic-go/qpack"]
    version = "v0.5.1"
    hash = "sha256-/r2LHWCfVD2vN3Vwso+El6fbQpy1xmQO4PwzHrfj2Lg="
  [mod."github.com/quic-go/quic-go"]
    version = "v0.54.0"
    hash = "sha256-RBhmZdiSHggY9uXvGBIlqwLVKG/3JwACSQ6BxzqRIq8="
  [mod."github.com/twitchyliquid64/golang-asm"]
    version = "v0.15.1"
    hash = "sha256-HLk6oUe7EoITrNvP0y8D6BtIgIcmDZYtb/xl/dufIoY="
  [mod."github.com/ugorji/go/codec"]
    version = "v1.3.0"
    hash = "sha256-MlEltg+EpDa20zLzdhEpE/t6gzBOA5icM/oTEEN/7Eo="
  [mod."go.uber.org/mock"]
    version = "v0.5.0"
    hash = "sha256-OLgbIRFUgt2taXypu5zSfnUZeeevNaU/myCdXBOBVaA="
  [mod."golang.org/x/arch"]
    version = "v0.20.0"
    hash = "sha256-10weU8aOKysmOCE7RRXXvXHkrw3fVDwM5qch2l+vFqQ="
  [mod."golang.org/x/crypto"]
    version = "v0.40.0"
    hash = "sha256-I6p2fqvz63P9MwAuoQrljI7IUbfZQvCem0ii4Q2zZng="
  [mod."golang.org/x/mod"]
    version = "v0.25.0"
    hash = "sha256-nW75iR1HL00GTFqWGxnJM/bFSa2vg4nlb3I/pFV10UA="
  [mod."golang.org/x/net"]
    version = "v0.42.0"
    hash = "sha256-YxileisIIez+kcAI+21kY5yk0iRuEqti2YdmS8jvP2s="
  [mod."golang.org/x/sync"]
    version = "v0.16.0"
    hash = "sha256-sqKDRESeMzLe0jWGWltLZL/JIgrn0XaIeBWCzVN3Bks="
  [mod."golang.org/x/sys"]
    version = "v0.35.0"
    hash = "sha256-ZKM8pesQE6NAFZeKQ84oPn5JMhGr8g4TSwLYAsHMGSI="
  [mod."golang.org/x/text"]
    version = "v0.27.0"
    hash = "sha256-VX0rOh6L3qIvquKSGjfZQFU8URNtGvkNvxE7OZtboW8="
  [mod."golang.org/x/tools"]
    version = "v0.34.0"
    hash = "sha256-UwxjYayFcN8il6e9s3UscRkPnZy9wE6NKGE0jS2mhG8="
  [mod."google.golang.org/protobuf"]
    version = "v1.36.9"
    hash = "sha256-i4zQhGFR6KprA5elLw33bA1VdMLAnL+Du3gBmrea+3Y="
